// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCST_0v1Xwo2R3QS-eBz3MM3PG3x6KBb4E',
    appId: '1:595287535519:android:8e5eda7a14e7e8fef357aa',
    messagingSenderId: '595287535519',
    projectId: 'cardboard-b1b34',
    databaseURL: 'https://cardboard-b1b34-default-rtdb.firebaseio.com',
    storageBucket: 'cardboard-b1b34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbarol15VWPWe3a4yN3_8y4eeZYhQ7GTM',
    appId: '1:595287535519:ios:82fdb406c89be0a3f357aa',
    messagingSenderId: '595287535519',
    projectId: 'cardboard-b1b34',
    databaseURL: 'https://cardboard-b1b34-default-rtdb.firebaseio.com',
    storageBucket: 'cardboard-b1b34.appspot.com',
    iosClientId: '595287535519-8t56r03ongqpt5lp9k8e2ch3f2s0i4db.apps.googleusercontent.com',
    iosBundleId: 'com.cardboard.app',
  );
}
